# Placement Prediction System
A placement prediction system is an innovative tool designed to forecast the likelihood of students securing job placements based on various factors such as academic performance, skills, and industry trends.

## About Dataset  

This dataset contains information about the students' academic and training and placement status.  

### Features  

- **CGPA**: The overall grades achieved by the student.  
- **Internships**: The number of internships a student has completed.  
- **Projects**: The number of projects a student has undertaken.  
- **Workshops/Certifications**: Indicates the courses that students have opted for to upskill themselves through various online platforms.  
- **Aptitude Test Score**: Scores from aptitude tests that assess a student's quantitative and logical thinking abilities, often part of the recruitment process.  
- **Soft Skill Rating**: Evaluates communication skills, which play a crucial role in placements and other aspects of life.  
- **Extra Curricular Activities**: Provides insight into an individual's personality by reflecting their involvement outside of academics.  
- **Placement Training**: The training provided to students in college to help them succeed in the placement process.  
- **SSC and HSC**: Marks obtained in Senior Secondary and Higher Secondary examinations.  
- **Placement Status**: The target column with two classes: "Placed" and "Not Placed."

### The very first thing I will do is collect the dataset into this jupyter notebok

In [1]:
#importing libraries
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('placementdata.csv')

In [3]:
df

,StudentID,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,1,7.5,1,1,1,65,4.4,No,No,61,79,NotPlaced
1,2,8.9,0,3,2,90,4.0,Yes,Yes,78,82,Placed
2,3,7.3,1,2,2,82,4.8,Yes,No,79,80,NotPlaced
3,4,7.5,1,1,2,85,4.4,Yes,Yes,81,80,Placed
4,5,8.3,1,2,2,86,4.5,Yes,Yes,74,88,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,7.5,1,1,2,72,3.9,Yes,No,85,66,NotPlaced
9996,9997,7.4,0,1,0,90,4.8,No,No,84,67,Placed
9997,9998,8.4,1,3,0,70,4.8,Yes,Yes,79,81,Placed
9998,9999,8.9,0,3,2,87,4.8,Yes,Yes,71,85,Placed
9999,10000,8.4,0,1,1,66,3.8,No,No,62,66,NotPlaced

In [4]:
df.head()

,StudentID,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,1,7.5,1,1,1,65,4.4,No,No,61,79,NotPlaced
1,2,8.9,0,3,2,90,4.0,Yes,Yes,78,82,Placed
2,3,7.3,1,2,2,82,4.8,Yes,No,79,80,NotPlaced
3,4,7.5,1,1,2,85,4.4,Yes,Yes,81,80,Placed
4,5,8.3,1,2,2,86,4.5,Yes,Yes,74,88,Placed

In [5]:
df.isnull().sum()

StudentID                    0
CGPA                         0
Internships                  0
Projects                     0
Workshops/Certifications     0
AptitudeTestScore            0
SoftSkillsRating             0
ExtracurricularActivities    0
PlacementTraining            0
SSC_Marks                    0
HSC_Marks                    0
PlacementStatus              0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  10000 non-null  int64
 1   CGPA                       10000 non-null  float64
 2   Internships                10000 non-null  int64
 3   Projects                   10000 non-null  int64
 4   Workshops/Certifications   10000 non-null  int64
 5   AptitudeTestScore          10000 non-null  int64
 6   SoftSkillsRating           10000 non-null  float64
 7   ExtracurricularActivities  10000 non-null  object
 8   PlacementTraining          10000 non-null  object
 9   SSC_Marks                  10000 non-null  int64
 10  HSC_Marks                  10000 non-null  int64
 11  PlacementStatus            10000 non-null  object
dtypes: float64(2), int64(7), object(3)
memory usage: 937.6+ KB

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'O':  # Ensure the column is of object type before transforming
         df[col] = le.fit_transform(df[col])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  10000 non-null  int64
 1   CGPA                       10000 non-null  float64
 2   Internships                10000 non-null  int64
 3   Projects                   10000 non-null  int64
 4   Workshops/Certifications   10000 non-null  int64
 5   AptitudeTestScore          10000 non-null  int64
 6   SoftSkillsRating           10000 non-null  float64
 7   ExtracurricularActivities  10000 non-null  int32
 8   PlacementTraining          10000 non-null  int32
 9   SSC_Marks                  10000 non-null  int64
 10  HSC_Marks                  10000 non-null  int64
 11  PlacementStatus            10000 non-null  int32
dtypes: float64(2), int32(3), int64(7)
memory usage: 820.4 KB

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, f1_score

# Example DataFrame setup (replace with your actual DataFrame)
# df = pd.read_csv('your_dataset.csv')

# Define features and target variable
X = df.drop('PlacementStatus', axis=1)
y = df['PlacementStatus']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(n_estimators=100),
    "Gradient Boosting": GradientBoostingClassifier(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
    "Support Vector Machine": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "Neural Network": MLPClassifier(max_iter=1000)
}

# Initialize the results dictionary
results = {}

# Train and evaluate models
for model_name, model in models.items():
    # Train the model
    model.fit(X_train, y_train)

    # Make predictions
    y_pred = model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Store metrics in the results dictionary
    results[model_name] = {
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1 Score': f1
    }

    # Print results
    print(f"{model_name} Accuracy: {accuracy:.4f}")
    print(f"{model_name} Precision: {precision:.4f}")
    print(f"{model_name} Recall: {recall:.4f}")
    print(f"{model_name} F1 Score: {f1:.4f}\n")

# Optionally, print the results dictionary
print("Results Summary:")
for model_name, metrics in results.items():
    print(f"{model_name}: {metrics}")

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression Accuracy: 0.7965
Logistic Regression Precision: 0.7462
Logistic Regression Recall: 0.7705
Logistic Regression F1 Score: 0.7582

Decision Tree Accuracy: 0.7205
Decision Tree Precision: 0.6603
Decision Tree Recall: 0.6691
Decision Tree F1 Score: 0.6647

Random Forest Accuracy: 0.7880
Random Forest Precision: 0.7583
Random Forest Recall: 0.7162
Random Forest F1 Score: 0.7366

Gradient Boosting Accuracy: 0.7895
Gradient Boosting Precision: 0.7509
Gradient Boosting Recall: 0.7355
Gradient Boosting F1 Score: 0.7431

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xgboost\core.py:158: UserWarning: [07:32:36] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

XGBoost Accuracy: 0.7670
XGBoost Precision: 0.7274
XGBoost Recall: 0.6993
XGBoost F1 Score: 0.7131

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Support Vector Machine Accuracy: 0.5860
Support Vector Machine Precision: 0.0000
Support Vector Machine Recall: 0.0000
Support Vector Machine F1 Score: 0.0000

K-Nearest Neighbors Accuracy: 0.7405
K-Nearest Neighbors Precision: 0.6828
K-Nearest Neighbors Recall: 0.6969
K-Nearest Neighbors F1 Score: 0.6898

Naive Bayes Accuracy: 0.7940
Naive Bayes Precision: 0.7281
Naive Bayes Recall: 0.8019
Naive Bayes F1 Score: 0.7632

Neural Network Accuracy: 0.7160
Neural Network Precision: 0.7425
Neural Network Recall: 0.4807
Neural Network F1 Score: 0.5836

Results Summary:
Logistic Regression: {'Accuracy': 0.7965, 'Precision': 0.7461988304093568, 'Recall': 0.7705314009661836, 'F1 Score': 0.7581699346405228}
Decision Tree: {'Accuracy': 0.7205, 'Precision': 0.6603098927294399, 'Recall': 0.6690821256038647, 'F1 Score': 0.6646670665866826}
Random Forest: {'Accuracy': 0.788, 'Precision': 0.7583120204603581, 'Recall': 0.716183574879227, 'F1 Score': 0.7366459627329193}
Gradient Boosting: {'Accuracy': 0.7895, 'Precision': 0.750924784217016, 'Recall': 0.7355072463768116, 'F1 Score': 0.7431360585723001}
XGBoost: {'Accuracy': 0.767, 'Precision': 0.7273869346733668, 'Recall': 0.6992753623188406, 'F1 Score': 0.7130541871921182}
Support Vector Machine: {'Accuracy': 0.586, 'Precision': 0.0, 'Recall': 0.0, 'F1 Score': 0.0}
K-Nearest Neighbors: {'Accuracy': 0.7405, 'Precision': 0.6828402366863905, 'Recall': 0.6968599033816425, 'F1 Score': 0.6897788404064554}
Naive Bayes: {'Accuracy': 0.794, 'Precision': 0.7280701754385965, 'Recall': 0.8019323671497585, 'F1 Score': 0.7632183908045977}
Neural Network: {'Accuracy': 0.716, 'Precision': 0.7425373134328358, 'Recall': 0.4806763285024155, 'F1 Score': 0.5835777126099707}

In [10]:
results=pd.DataFrame(results)
results

,Logistic Regression,Decision Tree,Random Forest,Gradient Boosting,XGBoost,Support Vector Machine,K-Nearest Neighbors,Naive Bayes,Neural Network
Accuracy,0.796500,0.720500,0.788000,0.789500,0.767000,0.586,0.740500,0.794000,0.716000
Precision,0.746199,0.660310,0.758312,0.750925,0.727387,0.000,0.682840,0.728070,0.742537
Recall,0.770531,0.669082,0.716184,0.735507,0.699275,0.000,0.696860,0.801932,0.480676
F1 Score,0.758170,0.664667,0.736646,0.743136,0.713054,0.000,0.689779,0.763218,0.583578

## cross fold validation

In [11]:

# Initialize the results dictionary
results = {}

# Train and evaluate models
for model_name, model in models.items():
    # Train the model
    model.fit(X_train, y_train)

    # Make predictions
    y_pred = model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Store metrics in the results dictionary
    results[model_name] = {
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1 Score': f1
    }

    # Print results
    print(f"{model_name} Accuracy: {accuracy:.4f}")
    print(f"{model_name} Precision: {precision:.4f}")
    print(f"{model_name} Recall: {recall:.4f}")
    print(f"{model_name} F1 Score: {f1:.4f}\n")

# Select the best model based on your metrics
best_model_name = "XGBoost"  # Replace with the model name having the best performance
best_model = models[best_model_name]

# Perform cross-validation on the best model
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(best_model, X, y, cv=5, scoring='accuracy')  # 5-fold cross-validation
print(f"{best_model_name} Cross-Validation Accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

# Retrain the best model on the entire training dataset
best_model.fit(X_train, y_train)

# Make predictions and evaluate on the test set
y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Retrained {best_model_name} Accuracy: {accuracy:.4f}")
print(f"Retrained {best_model_name} Precision: {precision:.4f}")
print(f"Retrained {best_model_name} Recall: {recall:.4f}")
print(f"Retrained {best_model_name} F1 Score: {f1:.4f}")

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression Accuracy: 0.7965
Logistic Regression Precision: 0.7462
Logistic Regression Recall: 0.7705
Logistic Regression F1 Score: 0.7582

Decision Tree Accuracy: 0.7190
Decision Tree Precision: 0.6591
Decision Tree Recall: 0.6655
Decision Tree F1 Score: 0.6623

Random Forest Accuracy: 0.7840
Random Forest Precision: 0.7526
Random Forest Recall: 0.7126
Random Forest F1 Score: 0.7320

Gradient Boosting Accuracy: 0.7895
Gradient Boosting Precision: 0.7509
Gradient Boosting Recall: 0.7355
Gradient Boosting F1 Score: 0.7431

XGBoost Accuracy: 0.7670
XGBoost Precision: 0.7274
XGBoost Recall: 0.6993
XGBoost F1 Score: 0.7131

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xgboost\core.py:158: UserWarning: [07:36:23] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Support Vector Machine Accuracy: 0.5860
Support Vector Machine Precision: 0.0000
Support Vector Machine Recall: 0.0000
Support Vector Machine F1 Score: 0.0000

K-Nearest Neighbors Accuracy: 0.7405
K-Nearest Neighbors Precision: 0.6828
K-Nearest Neighbors Recall: 0.6969
K-Nearest Neighbors F1 Score: 0.6898

Naive Bayes Accuracy: 0.7940
Naive Bayes Precision: 0.7281
Naive Bayes Recall: 0.8019
Naive Bayes F1 Score: 0.7632

Neural Network Accuracy: 0.7320
Neural Network Precision: 0.6233
Neural Network Recall: 0.8913
Neural Network F1 Score: 0.7336

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xgboost\core.py:158: UserWarning: [07:36:28] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xgboost\core.py:158: UserWarning: [07:36:28] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xgboost\core.py:158: UserWarning: [07:36:28] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xgboost\core.py:158: UserWarning: [07:36:28] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xgboost\core.py:158: UserWarning: [07:36:28] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xgboost\core.py:158: UserWarning: [07:36:29] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

XGBoost Cross-Validation Accuracy: 0.7213 ± 0.0966
Retrained XGBoost Accuracy: 0.7670
Retrained XGBoost Precision: 0.7274
Retrained XGBoost Recall: 0.6993
Retrained XGBoost F1 Score: 0.7131

In [13]:
from pycaret.classification import *
reg = setup(df, target='PlacementStatus')
best_model = compare_models()